server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/typeahead
    username: typeahead
    password: typeahead
    hikari:
      initialization-fail-timeout: 0
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
  flyway:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
