server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:55432/typeahead
    username: typeahead
    password: typeahead
    hikari:
      initialization-fail-timeout: 0
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    url: jdbc:postgresql://127.0.0.1:55432/typeahead
    user: typeahead
    password: typeahead
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  dataset:
    load: false
    path: ../data/queries.csv
    batch-size: 1000
    prefix-max-length: 50
